; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
    default_envs = d1_mini_debug

[env]
    ; Default settings for all environments
    upload_speed    = 460800
    monitor_speed   = 115200

[test]
    ; *****************************************************
    ; Settings for testing runtime
    ; *****************************************************
	framework  		= googletest
	lib_deps		= google/googletest@^1.17.0
	filter_embedded	= embedded/*
	filter_native	= native/*


[common]
    framework     = arduino
    build_flags   =
        -D TEMPLATE_PLACEHOLDER=36              ; $ sign for web templates instead of %
        '-D WIFI_DEFAULT_AP_SSID_PREFIX="LSC"'	; Default WIFI AP SSID Prefix
        '-D DEFAULT_DEVICE_NAME="LSC-Device"'   ; Default Device Name
        ; Allow to use #pragma directives in source code and enable exception handling
        ; in previous versions it was enabled by -fexceptions flag
        -Wno-unknown-pragmas
        -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
        -D RADIO_433_RECEIVER_PIN=D2

    board_build.ldscript    = eagle.flash.4m1m.ld 
    board_build.filesystem  = littlefs
    extra_scripts           = scripts/buildSteps.py

    lib_deps      =
        ArduinoJson
        LittleFS
        ESP32Async/ESPAsyncTCP
        ESP32Async/ESPAsyncWebServer
        AsyncMqttClient
        PLibESPV1

[common_esp8266]
	; Context of ESP8266 Devices...
    monitor_filters         = esp8266_exception_decoder

	lib_deps =
		ESP8266WiFi

	platform_packages =
		platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

[common_esp32]
	; Context of ESP32 Devices
	lib_deps =
		WiFi

       

[env:d1_mini_debug]
    platform        = espressif8266
    board           = d1_mini
    framework       = ${common.framework}
    build_type      = debug
    
    platform_packages		= ${common_esp8266.platform_packages}
    board_build.ldscript    = ${common.board_build.ldscript}
    board_build.filesystem  = ${common.board_build.filesystem}

    monitor_filters = 
        ${common_esp8266.monitor_filters}
        log2file


    extra_scripts           = ${common.extra_scripts}
    
    build_flags =
        ${common.build_flags}
        -D TRACE
        -D DEBUGVERSION					; Defines, that this is a debugversion    
        -D DEBUGINFOS					; Main Debug Info to enable Debug Macros
        -D NO_DEBUG_LSC_FILESYSTEM
        -D NO_DEBUG_LSC_SECURITY
        -D NO_DEBUG_LSC_APPL
        -D NO_DEBUG_LSC_STATUSHANDLER
        -D NO_DEBUG_LSC_CONFIGHANDLER
        -D NO_DEBUG_LSC_WIFI
        -D NO_DEBUG_LSC_HTLM_PAGES
        -D NO_DEBUG_LSC_BUTTON
        -D NO_DEBUG_LSC_WEBSERVER
        -D NO_DEBUG_LSC_WEBROUTES
        -D NO_DEBUG_LSC_WEBSOCKET
        -D NO_DEBUG_LSC_MQTT
        -D NO_DEBUG_LSC_RF433RECEIVER
        -D NO_DEBUG_LSC_DHT_SENSOR
        -D NO_DEBUG_LSC_DISPLAY
        -D NO_DEBUG_LSC_FRONTEND			; Debug the Frontend (WebGUI) - use the Web Developer Tools in the Browser

    lib_compat_mode     = strict
    lib_ldf_mode        = chain

    lib_deps = 
        ${test.lib_deps}
        ${common.lib_deps}
        ${common_esp8266.lib_deps}
        https://github.com/sui77/rc-switch

    ; Custom Serial Monitor speed (baud rate)

[env:d1_mini]
    platform    = espressif8266
    board       = d1_mini
    framework   = ${common.framework}
    build_type  = release

    platform_packages		= ${common_esp8266.platform_packages}
	board_build.ldscript	= ${common.board_build.ldscript}
    board_build.filesystem  = ${common.board_build.filesystem}
            
    extra_scripts = ${common.extra_scripts}
    build_flags =
            ${common.build_flags}
            -Wno-unused-value

    lib_compat_mode     = strict
    lib_ldf_mode        = chain

    lib_deps = 
        ${test.lib_deps}
        ${common.lib_deps}
        ${common_esp8266.lib_deps}
        https://github.com/sui77/rc-switch

        