/***************************************************************************
 * This file is generated by "buildPages v2.0.1"
 * Do not edit this file, it will be overwritten by the pageBuilder script.
 * The buildPages module is part of the PLibESPV1 project.
 * Build context: OnAir-Light
 ***************************************************************************/

/**
  @PageBuilder:register(InfoPage,CInfoPage)
 */

class CInfoPage extends CPageHandler {
    /**
     * 
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        // don't use this, before initialized !
        super("info",new CElement("#InfoPage"),oApp.Config);
        this._App = oApp;
       // this.Translator = new CTranslator();
    }

    LocalVars = new CVarTable();

    
    // #region Update Status on a regular base
    disposePage(pView, pApp) {
        super.disposePage(pView, pApp);
        this.RefreshTimer = clearInterval(this.RefreshTimer);
        this.RefreshTimer = null;
    }

    preparePage(pView, pApp) {
        super.preparePage(pView, pApp);
        // Set an interval to refresh the status infos every 5 seconds...
        this.RefreshTimer = setInterval( this.refreshStatus.bind(this, pView, pApp), 5000);
    }
    
    refreshStatus(pView, pApp) {
        pApp.requestActStatus();
    }

    /**
     * Triggered, when a new status message is received from the web socket.
     * @param {CView} pView 
     * @param {CApp} pApp 
     * @returns false to avoid loadPageConfig is called again (!) and the game starts again...
     */
    onUpdateStatusReceived(pView, pApp) {
        this.loadPageConfig(pView, pApp);
        return(false)
    }
    // #endregion

    /**
     * 
     * @param {*} pView 
     * @param {*} pApp 
     * @returns 
     * @overload
     */
    loadPageConfig(pView, pApp) {
        let oStatus = pApp.DeviceStatus;

        this.LocalVars.setVars(pApp.tVars);
        this.LocalVars.setVars(oStatus);
       
        // set the root element infos - no prefix...
        this.setConfigValues(pView,oStatus);
        for(let strName in oStatus) {
            let oData = oStatus[strName];
            if(oData && Utils.isObj(oData)) {
                this.setConfigValues(pView,oData,strName);
            }
        }
        let oLight = pView.gel(".OnAirLight");
        if(this.loadClientTable(pView,oStatus)) {
            oLight.ac("OnAirActive");
        } else {
            oLight.rc("OnAirActive");
        }
        pView.translate();
        return(oStatus);
    }

    /**
 * show the current client list in the status page
 * @param {*}  oClientList 
 */
    loadClientTable(pView,oDeviceStatus) {
        let bIsActive = false;
        let oClientList;
        if(oDeviceStatus && oDeviceStatus.onair) oClientList = oDeviceStatus.onair.clients;

        let oTranse = new CTranslator();
        let oTable = document.getElementById("client-table");
        const oNowMS = Date.now();
        const oDevActTimeMS = oNowMS - oDeviceStatus.now;
        const oDevActStartMS = oDevActTimeMS - oDeviceStatus.starttime;

        if(oTable) {
            oTable.innerHTML = "";
            if(!oClientList || oClientList.length == 0) {
                let oRow = oTable.insertRow(-1);
                ; let oCell = oRow.insertCell(0);
                EC(oRow.insertCell(0)).i18n("Info.noClients");
                // oTranse.translate(oCell,undefined,this.LocalVars);
                // oCell.innerHTML = oTranse.translateI18n("Info.noClients","---",this.LocalVars); // "No clients connected...";
            } else {
                for(let i=0; i < oClientList.length; i++) {
                    if(oClientList[i].isCamOn || oClientList[i].isMicOn) bIsActive = true;

                    let oRow = oTable.insertRow(-1);
                    EC(oRow.insertCell(0))
                        .ac("clientAddress")
                        .html(oClientList[i].client);            
                    EC(oRow.insertCell(1)).i18n(oClientList[i].isCamOn ? "Info.cam" : "Info.none");
                    EC(oRow.insertCell(2)).i18n(oClientList[i].isMicOn ? "Info.micro" : "Info.none");
                    const nLastUpd = oDevActStartMS + oClientList[i].lastUpd;
                    const oUpdDate = new Date(nLastUpd);
                    EC(oRow.insertCell(3)).setText(oUpdDate.toLocaleTimeString());
                }
            }
        }
        return(bIsActive);
    }

}
/**
  @PageBuilder:register(StatusPage,CStatusPage)
 */

class CStatusPage extends CPageHandler {
    /**
     * 
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        // don't use this, before initialized !
        super("status",new CElement("#StatusPage"),oApp.Config);
        this._App = oApp;
       // this.Translator = new CTranslator();
    }

        
    // #region Update Status on a regular base
    disposePage(pView, pApp) {
        super.disposePage(pView, pApp);
        this.RefreshTimer = clearInterval(this.RefreshTimer);
        this.RefreshTimer = null;
    }

    preparePage(pView, pApp) {
        super.preparePage(pView, pApp);
        // Set an interval to refresh the status infos every 5 seconds...
        this.RefreshTimer = setInterval( this.refreshStatus.bind(this, pView, pApp), 5000);
    }
    
    refreshStatus(pView, pApp) {
        pApp.requestActStatus();
    }

    /**
     * Triggered, when a new status message is received from the web socket.
     * @param {CView} pView 
     * @param {CApp} pApp 
     * @returns false to avoid loadPageConfig is called again (!) and the game starts again...
     */
    onUpdateStatusReceived(pView, pApp) {
        this.loadPageConfig(pView, pApp);
        return(false)
    }
    // #endregion




    /**
     * Load the page config...
     * Request an actual status from the device...
     * This will trigger an update message, which will be handled in onUpdate_status_Received.
     * @param {CView} pView 
     * @param {CApp} pApp 
     */
    loadPageConfig(pView, pApp) {
        let oStatus = pApp.DeviceStatus;
       
        // set the root element infos - no prefix...
        this.setConfigValues(pView,oStatus);
        for(let strName in oStatus) {
            let oData = oStatus[strName];
            if(oData && Utils.isObj(oData)) {
                this.setConfigValues(pView,oData,strName);
            }
        }

        let oVars = new CVarTable();
        oVars.setVars(pApp.tVars);
        oVars.setVars(oStatus);
        
        // now the usage bar
        let nAvailableSize = oStatus.flash_size - oStatus.fs_total;
        let nPercentUsed = (oStatus.sketch_size * 100) / nAvailableSize;
        let oUsageBar =  pView.sel("#flashUsage");
        if(oUsageBar) {
            oVars.setVar("flash_used_percent",~~nPercentUsed);
            oVars.setVar("flash_available",nAvailableSize);
            oUsageBar.style.width = nPercentUsed + "%";
            oUsageBar.innerText = ~~(oStatus.sketch_size / 1024) + " KB";
            let oUB = EC(oUsageBar);
            let oTranse = new CTranslator();
            let strI18n = "Status.memOK";
            if(nPercentUsed > 50) {
                oUB.rc("usageOK").ac("usageWarn");
                strI18n = "Status.memWarn";
            } else {
                oUB.ac("usageOK").rc("usageWarn");
            }
            oTranse.translateI18n(strI18n,undefined,oVars)
                .then(str => { 
                    oUB.attr("title",str)
                }
            )
        }
        return(oStatus);
    }

    
}
/**
 * The System Page with Restart / Reset
 * 
 * @PageBuilder:register(SystemPage,CSystemPage)
 */
class CSystemPage extends CPageHandler {
    constructor(oApp) {
        super("system",EC("#SystemPage"),oApp.Config);
        this._App = oApp;
        this.Transe = new CTranslator();
    }

    async restartDevice() {
        let strAsk = await this.Transe.getKeyData("System.Restart.confirm");
        if (confirm(strAsk ?? "restart ?")) {
            this._App.restartDevice();
            let oDlg = new CWaitDialog({
                title: "i18n:System.Restart.title",
                body: "i18n:System.Restart.waitmsg",
                onFinished: function() { location.href = location.href; }
            });
            oDlg.showModal();
        }
    }

    async resetDevice() {
        let strAsk = await this.Transe.getKeyData("System.Reset.confirm");
        if (confirm(strAsk ?? "reset ?")) {
            this._App.resetDevice();
            let oDlg = new CWaitDialog({
                title: "i18n:System.Reset.title",
                body: "i18n:System.Reset.waitmsg",
                onFinished: function() { location.href = location.href; }
            });
            oDlg.showModal();
        }
    }

    on(pView, oElement) {
        if(Utils.isElement(oElement)) {
            switch(oElement.id) {
                case "restart": this.restartDevice(); break;
                case "reset":   this.resetDevice(); break;
            }
        }
    }
}
/**
 * Represents a WiFi Setting page
 * 
 * @PageBuilder:register(WiFiPage,CWiFiPage) 
 */
class CWiFiPage extends CPageHandler {
    /**
     * 
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        // don't use this, before initialized !
        super("wifi",new CElement("#WiFiPage"),oApp.Config);
        this._App = oApp;
       // this.Translator = new CTranslator();
    }

    /**
     * catch the useWiFiBtn click event from the scan dialog to insert the selected network.
     * @param {CView} pView 
     * @param {HTMLElement} oElement 
     * @param {string} strCmd 
     */
    on(pView,oElement,strCmd) {
        super.on(pView,oElement);
        if(Utils.isElement(oElement)) {
            if(oElement.id == "useWifiBtn") {
                let oSource = pView.selById("scan_ssid");
                let oSelected = oSource.options[oSource.selectedIndex];
                if(oSelected) {
                    pView.sel("[data-cfg = 'ssid']").value  = oSelected.value;
                    pView.sel("[data-cfg = 'bssid']").value = oSelected.bssidvalue; 
                }
                this.closeDialog(pView,oElement);
            } 
            // Close action for modal dialog ?
            if(oElement.dataset.dismiss == "modal")  this.closeDialog(pView,oElement);
        }
        
    }

    /**
     * listen on the web socket message and check if the message is a "ssidlist" message.
     * @param {CView} pView 
     * @param {object} oMsg 
     */
    onSocketMessage(pView, oMsg) {
        if(oMsg && oMsg.data == "ssidlist") {
            this.insertFoundNetworks(oMsg.payload);
        }
    }

    /**
     * display the scan network dialog.
     * @param {CView} pView 
     * @param {HTMLElement} oElement
     */
    showScanDialog(pView,oElement) {
        let oThis = this;
        let oDlg = new CDialog("#scanWiFiDialog", { cancelBtn:true });
        // Reset to scan start....
        try { oDlg.sel(".dialogHeader").dataset.i18n = "WiFi.scan.title"; } catch {}
        try { oDlg.sel("#scan_ssid").innerHTML = ""; } catch {}
        this._App.Translator.translate(oDlg.getBase())
            .then(e => {
                oDlg.showModal();
                oThis._App.sendSocketCommand(DEFAULTS.SCAN_WIFI);
            });
    }

    /**
     * insert the found (scanned) networks into the select element.
     * @param {*} oListOfSSIDs 
     */
    insertFoundNetworks(oListOfSSIDs) {
        let oDlg = new CDialog("#scanWiFiDialog");
        let oSelect = oDlg.sel("#scan_ssid");
        try { oDlg.sel(".dialogHeader").dataset.i18n = "WiFi.scan.titleDone"; } catch {}
        this._App.Translator.translate(oDlg.getBase())
            .then(e => {
                for(let i=0; i < oListOfSSIDs.length; i++) {
                    let x = parseInt(oListOfSSIDs[i].rssi);
                    let nPercent = Math.min(Math.max(2 * (x + 100), 0), 100);
                    let oOpt = document.createElement("option");
                    oOpt.value = oListOfSSIDs[i].ssid;
                    oOpt.bssidvalue = oListOfSSIDs[i].bssid;
                    oOpt.innerHTML = oListOfSSIDs[i].ssid + " (" + nPercent + "%) - " + oListOfSSIDs[i].bssid ;
                    oSelect.appendChild(oOpt);
                }
            });
        
        
    }
}


/**
 * Page Handler class for Backup / Restore Page
 * 
 * @PageBuilder:register(BackupPage,CBackupPage)
 */

class CBackupPage extends CPageHandler {
    constructor(oApp) {
        super("backup",document.getElementById("BackupPage"),oApp.Config)
        this._oApp = oApp;
    }

    /**
     * catch the button click events.
     * @param {*} oContent 
     * @param {*} oElement 
     * @param {*} strCmd 
     */
    on(oContent,oElement,strCmd) {
        super.on(oContent,oElement);
        // Backup requested ? - ask the device for a backup file... (catch the result...)
        if(Utils.isElement(oElement)) {
            switch(oElement.id) {
                case "backupSet": 
                    this._oApp.sendSocketCommand(DEFAULTS.GET_BACKUP_COMMAND);
                    break;
                case "restoreSet": 
                    let oAlert = new CAlertDialog({ title: "i18n:SysCfg.Restore.title"})
                    if ("files" in oElement) {
                        if (oElement.files.length === 0) {
                            oAlert.showModal({ body: "i18n:main.noFileSelected"});
                            // alert("You did not select file to restore!");
                        } else {
                            let oReader = new FileReader();
                            oReader.onload = function() {
                                try {
                                    let oConfigData = JSON.parse(oReader.result);
                                    // Check if structure could be a config file...
                                    if (oConfigData.wifi && oConfigData.wifi.hasOwnProperty("ap_mode")) {
                                        if (confirm("File seems to be valid, do you wish to continue?")) {
                                            this.m_oAPP.WS.sendCommandMessage(RESTORE_BACKUP_COMMAND,"",oConfigData);
                                        }
                                    } else {
                                        oAlert.showModal({body: "i18n:SysCfg.Restore.invalidFile"});
                                        // alert("Not a valid backup file!");
                                    }
                                } catch (e) {
                                    oAlert.showModal({body: "i18n:SysCfg.Restore.invalidFile"});
                                    // alert("Invalid backup file!");
                                return;
                                }
        
                            };
                            oReader.readAsText(oElement.files[0]);
                        }
                    }    
                    break;
            }
        }
    }
    
     /**
     * listen on the socket message and check if the message is a "ssidlist" message.
     * @param {*} pView 
     * @param {*} oMsg 
     */
    onBackupMessageReceived(pView, oMsg) {
        if(oMsg) {
            switch(oMsg.data) {
                case "config":  // A backup request for config received...
                    // Simulate a download click...
                    let oDataObj = oMsg.payload;
                    let strData =  "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(oDataObj, null, 2));
                    let dlAnchorElem = pView.selById("downloadSet");
                    dlAnchorElem.setAttribute("href", strData);
                    dlAnchorElem.setAttribute("download", `${this._oApp.Vars.getValue("prog_name")} - settings.json`);
                    dlAnchorElem.click();
                    break;
            }
        }
    }
}
/**
 * Firmware Download / Install page
 * 
 * @PageBuilder:register(FirmwarePage,CFirmwarePage)
 */
class CFirmwarePage extends CPageHandler {
    _fwInstTime = 30;   // Time needed to install firmware..
    constructor(oApp) {
        super("firmware",EC("#FirmwarePage"),oApp.Config);
        this._App = oApp;
        
    }

    loadPageConfig(pView, pApp) {
        super.loadPageConfig(pView,pApp);
        EC("#fwSelect").on("change",this.onFile.bind(this));
        let strURL = pApp.Settings.getData("app.latest.url");
        fetch(strURL)
            .then((response) => {
                return response.json();
            })
            .then((oRelease) => {
                let oAsset = oRelease.assets[0];
                let oDTCreated = new Date(oAsset.created_at);
                let oDTUpdated = new Date(oAsset.updated_at)
                pView.sel("#Date").textContent = oDTCreated.toLocaleDateString() + " / " + oDTUpdated.toLocaleDateString();
                pView.sel("#Name").textContent = oRelease.name;
                pView.sel("#Version").textContent = oRelease.tag_name;
                pView.sel("#Desc").innerHTML = oRelease.body.replaceAll("\n","<br/>");
                pView.gel("#downloadupdate").attr("href",oAsset.browser_download_url);
                pView.sel("#download").disabled = false;
            })
            .catch(ex => {
            });

    }
    onFile(oEvt) {
        EC("#fwInstall").getBase().disabled = false;
    }

    on(pView, oElement) {
        if(oElement) {
            switch(oElement.id) {

                case 'download':
                    // A firmware download was clicked, trigger the download...
                    pView.sel("#downloadupdate").click();
                    break;

                case 'fwSelect':
                    // A Firnware was selected, enable the install button
                    let oFW = pView.sel('#fwInstall');
                    oFW.disabled = false;
                    break;

                case 'fwInstall':
                    // Install the selected Firmware file
                    
                    // formData.append("bin", pView.sel("#fwSelect").files[0]);
                    
                    let oDlg = new CWaitDialog({
                        title: "installing firmware - please wait",
                        timeOutSecs: this._fwInstTime,
                        onFinished: function() { location.href = location.href; }
                    });
                    oDlg.showModal();
                    let oFile = pView.sel("#fwSelect").files[0];
                    let oFormData = new FormData();
                    oFormData.append("bin", oFile, oFile.name);
                    
                    fetch('/update',{ 
                        method:'POST', 
                        body: oFormData
                    });
                    break;
            }
        }
    }

}
// #region RF433 Module definition (script)

/** 
 * RF433 names and constants
 */
const RF433 = {
    "DIALOG"            : "editRF344Dialog",
    "SCAN"              : "scanRF433",
    "ONAIR_CAMERA"      : 0,
    "ONAIR_MICRO"       : 1,
    "ONAIR_DEVICE_ON"   : 1,
    "ONAIR_DEVICE_OFF"  : 0
}

/**
 * Dialog Class to edit the RF433 remotes
 */
class CRF433Dialog extends CDialog {
    /**
     * Constructor with or without data.
     * If no data, it is only a frame to manipulate the dialog data
     * like from the scanRF433 result.
     * @param {object} oData 
     * {
     *      mode: "edit"    // see language file
     *      on: 12345       // code of the remote
     *      msg: 0/1        // cam or mic
     *      cmd: 0/1        // command on / off
     *      srcID:  undefined/strID // If edit, the id of the row to be edited..
     *      
     * }
     */
    constructor(oData) {
        super("#" + RF433.DIALOG, { cancelBtn:true });
        if(oData) {
            let i18nPrefix = "RF433." + oData.mode;
            try { 
                this.gel(".dialogHeader").i18n(i18nPrefix +  ".title");
                // Keep data at last... if srcID is undefined, data is a query, not a set !
                this.gel("#dlg_on")
                        .reset()
                        .setValue(oData.on ?? "")
                        .on("keyup",this.checkValidity.bind(this),"textKeyUp")
                        .data("srcID",oData.srcID);

                this.gel("#dlg_msg").setValue(oData.msg ?? RF433.ONAIR_CAMERA); 
                this.gel("#dlg_cmd").setValue(oData.cmd ?? RF433.DEVICE_ON);
            } catch {}        
            this.checkValidity();
        }
    }

    /**
     * To set a random code (number string),
     * so the validation stays valid, when the dialog is inactive
     * @param {string} nCode 
     */
    setScanCode(nCode) {
        if(nCode) {
            this.gel("#dlg_on").setValue(nCode);
            this.checkValidity();
        }
    }

    /**
     * Checks the validity of the Dialog code field and enables/disable the save btn.
     */
    checkValidity() {
        EC("#setRF433Btn").enable(EC("#dlg_on").isValid());
    }
}

/***
 * 
 * RF433 Settings page
 * 
 * >> Tell the page builder to register this class as handler for page with id "RF433Page"
 * @PageBuilder:register(RF433Page,CRF433Page)
 * 
 */
class CRF433Page extends CPageHandler {

    /**
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        super("rf433",new CElement("#RF433Page"),oApp.Config);
        this._App = oApp;
    }

      /**
     * show the RF433 Control Code Dialog (edit / add)
     * The dialog will be translated before it is shown...
     * At least the mode has to be set to edit or new, so
     * the translation of the dialog is correct.
     * If you want to use other modes, update the language files.
     * @param {object} oOptions 
     */
    _showDialog(oOptions) {
        if(Utils.isObj(oOptions)) {
            let oDlg = new CRF433Dialog(oOptions);
            this._App.Translator.translate(oDlg.getBase())
            .then(e => {
                oDlg.showModal();
            });
        }
    }

    /**
     * entry point to load config data
     * @param {CView} pView 
     * @param {CAPP} pApp 
     * @returns the config of this page
     * @overload
     */
    loadPageConfig(pView, pApp) {
        super.loadPageConfig(pView,pApp);
        this._pCurrentView = pView;
        this._pCurrentApp  = pApp;
        let oConfig = this.getConfig(false);

        if(pApp && oConfig && oConfig.msgs) {
            for(let oMsg of oConfig.msgs) {   
                this._appendRFCode(pView,oMsg.on,oMsg.msg,oMsg.type);
            }
        }
        return(oConfig);
    }

    saveConfigValues(pView,oCfg,strPrefixName) { 
        if(pView && Utils.isObj(oCfg)) {
            this.saveElementToConfig(pView.sel("[data-cfg = 'enabled']"),oCfg,strPrefixName);
            oCfg.msgs = [];
            pView.gelAll("tr").forEach(oRow => {
                let oMsg = {}
                oMsg.on = oRow.data("on");
                oMsg.msg = oRow.data("msg");
                oMsg.type = oRow.data("cmd");
                if(oMsg.on) oCfg.msgs.push(oMsg);
            });

        }
    }

    /**
     * Generates a unique id of the row with this (remote) code...
     * @param {integer} nCode 
     * @returns 
     */
    _getRowID(nCode) {
        return("rf433_msg_" + nCode);
    }
    
    /**
     * Appen a row to the remote table
     * @param {CView} pView 
     * @param {string/integer} nOn 
     * @param {string/integer} nMsg 
     * @param {string/integer} nCmd 
     */
    _appendRFCode(pView, nOn,nMsg,nCmd) {
        let oTableBody =  pView.gel("#knownCodes");    
        if(oTableBody.hasBase()) {
            let strID = this._getRowID(nOn);
            let oRow = this._pCurrentView.gel("#" + strID);
            if(oRow.hasBase()) oRow.html("");
            else {
                oRow = oTableBody.cce("tr");
                oRow.ac("rf433-msgRow")
            }
            this._setRowData(oRow,nOn,nMsg,nCmd);
        }
    }

    /**
     * Set the data of this row.
     * Already existing data will be replaced (even the id of the row)
     * The row will be translated after creating the elements
     * @param {CView}  pView 
     * @param {CElement} oRow 
     * @param {integer} nOn 
     * @param {integer} nMsg 
     * @param {integer} nCmd 
     */
    _setRowData(oRow, nOn, nMsg, nCmd) {

        let strDevice = (nMsg    == RF433.ONAIR_CAMERA    ? "cam" : "mic");
        let strCmd    = (nCmd    == RF433.ONAIR_DEVICE_ON ? "on" : "off");
        let strID     = this._getRowID(nOn);
        oRow.id(strID);
        oRow.html("");
        oRow.data("on",nOn).data("msg",nMsg).data("cmd",nCmd);
        oRow.cce("td").attr("title","" + nOn).html("0x" + (nOn.toString(16)));
        oRow.cce("td").i18n("RF433." + strDevice).html(strDevice);
        oRow.cce("td").i18n("RF433." + strCmd).html(strCmd);

        oRow.cce("td")
            .cce("button")
            .id("edit_" + strID)
            .attr("class","btn btn-primary btn-sm pull-right rf433-enabled")
            .attr("style","width:5em")
            .data("i18n","RF433.edit")
            .on("click",this._editReceiver.bind(this),strID);

        oRow.cce("td")
            .cce("button")
            .id("del_" + strID)
            .attr("class","btn btn-danger btn-sm pull-right rf433-enabled")
            .attr("style","width:5em")
            .data("i18n","RF433.del")
            .on("click",this._deleteReceiver.bind(this),strID);

        this._App.Translator.translate(oRow);
    }

    /**
     * Edit the receiver.
     * Triggered by the generated "Edit" button of a single row
     * @param {PointerEvent} pPointerEvent 
     */
    _editReceiver(pPointerEvent) {
        let strSrcID = EC(pPointerEvent.currentTarget).evtArgs();
        let oElement = this._pCurrentView.gel("#" + strSrcID)
        this._showDialog({
            "mode": "edit",
            "srcID": strSrcID,
            "on" : oElement.data("on"),
            "msg" : oElement.data("msg"),
            "cmd": oElement.data("cmd"),
            "pView": this._pCurrentView,
            "pPageHandler": this,
            "oElement": oElement
        }); 
    }

     /**
     * Delete button of a row is pressed...
     * @param {PointerEvent} oPointerEvent 
     */
    _deleteReceiver(oPointerEvent) {
        let oElement = EC(oPointerEvent.currentTarget);
        let strRFID  = oElement.evtArgs();
        let oRow = this._pCurrentView.sel("#" + strRFID );
        if(oRow) { oRow.remove(); this._bIsModified = true; }
    }
  
    /**
     * catch the click events from the page and the dialog.
     * Called by the application / view handling
     * @param {CView} pView 
     * @param {HTMLElement} oElement 
     * @param {string} strCmd 
     */
    on(pView,oElement,strCmd) {
        super.on(pView,oElement);
        if(Utils.isElement(oElement)) {
            switch(oElement.id) {
                case "addRF433Btn":
                    this._showDialog({"mode": "add"}); 
                    break;
                case "setRF433Btn": 
                        // use button pressed - button event args are
                        // either the id of row to be edited or empty,
                        // if it should be a new row (add)
                        let oCodeElement = pView.gel("#dlg_on");
                        let nOn  = parseInt(oCodeElement.getValue());
                        let nMsg = parseInt(pView.gel("#dlg_msg").getValue());
                        let nCmd = parseInt(pView.gel("#dlg_cmd").getValue());
                        let strSrcRowID = oCodeElement.data("srcID");
                        let oRow = pView.gel("#" + strSrcRowID);
                        if(oRow.hasBase()) {
                            // If there is a source in place, set the new/org id to the row
                            // So it will be replaced instead of appended when changed.
                            oRow.id(this._getRowID(nOn));
                            this._setRowData(oRow,nOn,nMsg,nCmd);
                        } else {
                            this._appendRFCode(pView,nOn,nMsg,nCmd);
                        }
                        this._bIsModified = true;
                        this.closeDialog(pView,oElement);
                        break;
                case "scanRF433": 
                    this._App.sendSocketCommand(RF433.SCAN);
                    break;
            } 

            // Close action for modal dialog ?
            if(oElement.dataset.dismiss == "modal") {
                (new CRF433Dialog()).setScanCode("9")
                this.closeDialog(pView,oElement);
            } 
        }
    }

    /**
     * listen on the web socket message and check if the message is a "rf433code" message.
     * @param {CView} pView 
     * @param {object} oMsg 
     */
    onSocketMessage(pView, oMsg) {
        // Scan result code received...
        // insert it into the modal dialog code field...
        if(oMsg && oMsg.data == "rf433code" && oMsg.payload) {
            let oDlg = (new CRF433Dialog());
            oDlg.setScanCode(oMsg.payload.on)
        }
    }
}

// #endregion


// Page Handler Registration
function registerPageHandler(pApp) {
    pApp.registerPageHandler("InfoPage",new CInfoPage(pApp));
    pApp.registerPageHandler("StatusPage",new CStatusPage(pApp));
    pApp.registerPageHandler("SystemPage",new CSystemPage(pApp));
    pApp.registerPageHandler("WiFiPage",new CWiFiPage(pApp));
    pApp.registerPageHandler("BackupPage",new CBackupPage(pApp));
    pApp.registerPageHandler("FirmwarePage",new CFirmwarePage(pApp));
    pApp.registerPageHandler("RF433Page",new CRF433Page(pApp));
}

// End of Page Handler Registration
