#pragma once
/**
 * Defines all default settings for the application
 * Specify in the compile settings the necessary overrides "-D ...." switches.alignas
 * ProgVersion.h is generated by the build process and contains the version and the build number
 *
 */
#include <ProgVersion.h>
#define APP_AUTHOR      "P. Liebl"
#define APP_DESCRIPTION "A simple light that indicates when you are 'on air'."
#define APP_COPYRIGHT   "2025" 


/// File to store the configuration
/// Do NOT use the F("") Macro - LittleFS gets in trouble ! (Exception 3)
#ifndef CONFIG_FILE
    #define CONFIG_FILE "/config.json"
#endif

/// Data PIN of the RF433 Receiver 
#ifndef RADIO_433_RECEIVER_PIN
  #define RADIO_433_RECEIVER_PIN D2
#endif



#define APP_NAME        PROG_VERSION_NAME
// Debug Version has an attached "-D" to the version number
#ifdef DEBUGVERSION
    #define APP_VERSION PROG_VERSION_LONG"-D"
    #pragma warn "You are compiling the DEBUG Version : " APP_VERSION
#else
    #define APP_VERSION     PROG_VERSION_LONG
#endif



// Define the JsonDocument size to use, when config is mapped to it
// #define CONIFG_AS_JSON_SIZE 1024
#include <ConfigHandler.h>

struct AppConfig {
    unsigned long AutoRestartTime = 0L;
};

class CAppConfig : public CConfigHandler, public AppConfig {
        
    public:
        void writeConfigTo(JsonObject &oCfg, bool bHideCritical) override;
        void readConfigFrom(JsonObject &oCfg) override;
};



